title: "Arianna M. Varuolo-Clarke, Ph.D."
author: "Arianna Varolo-Clarke"
description: "NOAA Climate & Global Change Postdoctoral Fellow hosted by CIRES at the University of Colorado, Boulder" 
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Styling

dark_header: true          # always keep the header dark
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "publications.md", title: "Publications"}
  - {url: "/varuolo-clarke_CV_20240109.pdf", title: "CV"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/amvaruolo-clarke"}
  - {title: Twiter, icon: twitter, url: "https://twitter.com/amv_aruolo"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
